export const key = {
"id": "ID",
"vk": "ID ВК",
"number": "Номер телефона",
"fio": "ФИО",
"facebook": "Facebook",
"nickname": "Никнейм",
"domain": "Домен ВК",
"city": "Город",
"mobile_phone": "Номер телефона",
"home_phone": "Номер телефона",
"site": "Личная страница",
"status": "Статус ВК",
"followers_count": "Кол-во подписчиков",
"occupation": "Место работы",
"sex": "Пол",
"tv": "ТВ ВК",
"about": "Примечание",
"career": "Карьера",
"university_name": "Название университета",
"faculty_name": "Название факультета",
"education_form": "Форма обучения",
"education_status": "Статус обучения",
"home_town": "Адрес",
"universities": "Университет",
"schools": "Школа",
"relatives": "Родственники",
"skype": "Скайп",
"facebook_name": "Имя Facebook",
"instagram": "Страница в Instagram",
"relation_partner": "Родственники",
"livejournal": "Лайв журнал",
"timezone": "Временная зона",
"date_of_birth": "Дата рождения",
"no_valid_vk": "Нетепичный ВК",
"no_valid_number": "Нетепичный номер",
"no_valid_facebook": "Нетепичный Facebook",
"no_valid_fio": "Нетепичный ФИО",
"name": "Имя",
"name_table": "Название таблицы",
"info": "Доп. информация",
"country": "Страна",
"access_level": "Уровень доступа",
"type": "Доп. информация",
"updated_at": "Дата обновления",
"created_at": "Дата создания",
"mail": "Email",
"password": "Пароль",
"no_valid_mail": "Нетипичная Email",
"address": "Адрес",
"login": "Логин",
"none_type_name": "Нетипичное имя",
"snils": "СНИЛС",
"answer": "Ответ",
"payment_method": "Способ оплата",
"date": "Дата",
"no_valid_snils": "Нетепичный СНИЛС",
"vk_name": "ВК имя",
"inn": "ИНН",
"passport": "Паспорт",
"none_type_pasport_numb": "Нетипичный номер паспорта",
"enforcement_proceedings": "Исполнительное производство",
"start_date_enf_proc": "Дата начала исполн.производства",
"enf_proc_numb": "Номер исполнительного производства",
"debt": "Задолжность",
"no_valid_inn": "Нетепичный ИНН",
"no_valid_passport": "Нетепичные паспортные данные ",
"card_number": "Номер банковской карты",
"year": "Год",
"payment_system": "Тип платежной системы",
"bank": "Название банка",
"region": "Адрес",
"no_valid_date_of_birth": "Нетепичная дата рождения",
"gender": "Пол",
"date_registered": "Дата регистрации (создания)",
"location": "Зона",
"hometown": "Город",
"education_last_year": "Образование",
"relationship_status": "Статус отношений",
"work_place": "Место работы",
"last_update": "Последнее изменение",
"address_registration": "Адрес регистрации",
"lat": "Широта",
"lon": "Долгота",
"card_id": "ID карты",
"created_date": "Дата регистрации (создания)",
"airline_name": "Название авиакомпании",
"ticket_date": "Дата билета",
"city_from": "Из (город)",
"city_to": "В (город)",
"telegram": "ID Telegram",
"no_valid_telegram": "Нетепичный ID Telegram",
"adress": "Адрес",
"username": "Имя пользователя",
"information": "Доп. информация",
"sum": "Сумма",
"count_tovar": "Граф товара",
"category": "Категория товара",
"source": "Платформа продажи",
"name_replace": "Нетепичное имя",
"phone_client": "Номер телефона",
"auto": "Модель автомобиля",
"sms_status": "СМС сообщение",
"description": "Комментарий клиента",
"order_number": "Номер заказа",
"address_coord": "Адрес доставки",
"delivery_cost": "Стоимость доставки",
"insurance_number": "Страховой номер",
"passport_issued_by": "Паспортные данные",
"reg_date": "Дата регистрации",
"photo": "Фото",
"url": "Ссылка",
"title": "Название",
"price": "Цена",
"code": "Код",
"comment": "Комментарий",
"phone_contragent": "Номер телефона",
"phone_mob": "Номер телефона",
"phone_dop": "Номер телефона",
"phone_work": "Номер телефона",
"shop": "Название магазина",
"non_type_name": "Нетепичное имя",
"geo": "Адрес",
"year_birth": "Год рождения",
"s_fio": "ФИО отправителя",
"s_mail": "Email отправителя",
"mail_text": "Текст письма",
"check_word": "Контрольное значение",
"post_code": "Почтовый индекс",
"last_login": "Последняя регистрация",
"b_place": "Место рождения",
"last_date": "Последняя дата (активность)",
"passport_info": "Данные паспорта",
"ip": "IP",
"imei": "IMEI",
"imsi": "IMSI",
"no_valid_imei": "Нетепичный IMEI",
"no_valid_imsi": "Нетепичный IMSI",
"fraud": "Мошенники",
"age": "Возраст",
"profession": "Профессия",
"salary": "Желаемый доход",
"education": "Образование",
"languages": "Язык",
"metro": "Ближайшее метро",
"driver_license": "Номер водит. удостоверения",
"resume_date": "Дата возвращения",
"ticket_time": "Время билета",
"airport_from": "Из (аэропорт)",
"airport_to": "В (аэропорт)",
"buy_date": "Дата покупки",
"flights": "Данные полета",
"work_post": "Должность",
"work_dep": "Отдел",
"post": "Должность",
"company": "Компания",
"departament": "Департамент",
"manager": "Ведущий менеджер",
"host": "Домен",
"main_uri": "Основной WEB-адрес",
"user_login": "Логин",
"telegram_token": "Токен Telegram",
"password_hash": "Пароль",
"salt": "\"Cоль\"",
"fax": "Факс",
"cards": "Карта",
"passport_date": "Дата выдачи паспорта",
"passport_reg": "Данные паспорта",
"passport_expired": "Срок истечения паспорта",
"card_date": "Дата действий карты",
"postcode": "Почтовый индекс",
"grz": "Гос.рег.знак",
"vin": "VIN номер",
"numb_policy": "Номер страхового полиса",
"dtp_date": "Дата ДТП",
"no_valid_grz": "Нетипичный гос.рег.знак",
"no_valid_vin": "Нетипичный VIN номер",
"address_fact": "Адрес",
"address_real": "Адрес",
"subDivisionCode": "Код подразделения",
"FnsRegisteredFullName": "Полное название компании",
"FnsRegisteredShortName": "Короткое название компании",
"last_open_ip": "Последний ip",
"last_open_date": "Дата последней авторизации",
"last_click_date": "Дата последней активности",
"last_sent_date": "Дата последнего сообщения",
"discount_card": "Дисконтная карта",
"last_log_date": "Дата последней авторизации",
"update_date": "Дата обновления",
"barcode": "Код товара",
"brend": "Название бренда",
"organization": "Организация",
"date_create": "Дата регистрации (создания)",
"address_urid": "Адрес",
"okved": "ОКВЕД",
"type_activity": "Тип активности",
"pdate": "Дата",
"link": "Ссылка",
"text": "Текст",
"note": "Доп. информация",
"create_date": "Дата регистрации (создания)",
"parking_zone_numb": "Номер парковочной зоны",
"start_parking": "Начало паркинга",
"stop_parking": "Конец паркинга",
"anket_table": "Таблица анкет",
"product": "Банковский продукт",
"sum_request": "Запрошенная сумма",
"approved_limit": "Утвержденный лимит",
"sum_issue": "Выданная сумма",
"work": "Работа",
"number_work": "Номер телефона",
"number_house": "Номер телефона",
"money_income": "Доход",
"delivery_name": "Город доставки",
"issuer_passport": "Паспортные данные",
"prof": "Профессия",
"modif_date": "Дата последних изменений",
"passport_data": "Дата выдачи паспорта",
"surname_uk": "Фамилия (укр)",
"name_uk": "Имя (укр)",
"patronymic_uk": "Отчество (укр)",
"passport_details": "Данные паспорта",
"license_number": "Номер водит. удостоверения",
"license_details": "Данные водит. удостоверения",
"employer": "Работодатель",
"phone_house": "Номер телефона",
"sts": "Номер СТС",
"pts": "Номер ПТС",
"pasport_data": "Данные паспорта",
"type_operation": "Тип операции",
"pts_date": "Дата регистрации ПТС",
"numb_kuzov": "Номер кузова автомобиля",
"numb_shassi": "Номер шасси автомобиля",
"numb_dvig": "Номер двигателя автомобиля",
"car": "Модель автомобиля",
"car_color": "Цвет автомобиля",
"car_year": "Год выпуска автомобиля",
"actual_grz": "Актуальный гос.рег.знак",
"old_grz": "Старый гос.рег.знак",
"car_v": "Объем двигателя",
"car_ls": "Лошадиные силы",
"no_valid_sts": "Нетепичный СТС",
"no_valid_pts": "Нетепичный ПТС",
"friends": "Друзья",
"limit": "Кредитный лимит",
"account_number": "Номер аккаунта",
"avto": "Модель автомобиля",
"country_reg": "Страна регистрации",
"reg_passport": "Регистрация паспорта",
"pl_birth": "Место рождения",
"passport_vid": "Данные паспорта",
"relev_date": "Дата (актуальность)",
"service": "Подразделение",
"name_replic": "Название салона",
"owner": "Продавец",
"model": "Модель авто",
"year_of_production": "Год производства",
"mileage": "Пробег",
"modific": "Модификация двигателя",
"type_engine": "Тип двигателя (топлива)",
"privod": "Привод",
"type_kuzov": "Тип кузова",
"control": "Руль",
"color": "Цвет",
"condition": "Состояние",
"fraud_date": "Дата мошенничества",
"wildberries_id": "ID",
"wildberries_comment": "Коментарий",
"wildberries_lat": "Широта",
"wildberries_lon": "Долгота",
"last_login_time": "Дата последней активности",
"premium": "Наличие премиума",
"avatar": "Аватар",
"stories": "Доп. информация",
"section": "Раздел",
"note_apteka": "Данные аптеки",
"password_md5": "Пароль",
"insurance_product": "Страховой продукт",
"insurance_sum": "Страховая сумма",
"register_date": "Дата регистрации (создания)",
"passport_note": "Данные паспорта",
"insurance_company": "Страховая компания",
"type_use": "Тип использования",
"dop_lic": "Допущенно водителей",
"school": "Школа",
"learner": "Должность (преподаватель)",
"last_ip": "Последний ip адрес",
"poker_nickname": "Никнейм в покере",
"first_deposit_date": "Дата первого пополнения аккаунта",
"document": "Паспортные данные",
"favorite_category": "Любимая категория",
"favorite_dish": "Любимое блюдо",
"none_type_surname": "Нетепичное имя",
"none_type_patronymic": "Нетепичная фамилия",
"additionInfo": "Доп. информация",
"updatedAt": "Дата обновления",
"work_address": "Адрес",
"reg_adress": "Адрес",
"dr_lic_number": "Номер водительского удостоверения",
"dr_lic_date": "Дата выдачи вод.удостоверения",
"none_valid_note": "Доп. информация",
"card_numb": "Номер банковской карты",
"amount": "Сумма",
"content": "Отзыв",
"place_of_birth": "Место рождения",
"basis": "Основание",
"relation": "Родственники",
"airline_flight": "Номер полета",
"division_code": "Код подразделения",
"other_information": "Доп. информация",
"indif": "Идентификационный номер",
"work_number": "Номер телефона",
"home_number": "Номер телефона",
"citizen": "Гражданство",
"national": "Национальность",
"call_time": "Дата звонка",
"checkword": "Проверочное слово",
"passport_code": "Код подразделения",
"contacts": "Контакт",
"money": "Сумма кредита",
"srok": "Срок кредита",
"address_comment": "Комментарий к адресу",
"BIK": "БИК",
"bank_name": "Название банка",
"reg_document": "Документы",
"director_name": "Имя руководителя",
"office": "Номер офиса",
"KPP": "КПП",
"d_date": "Дата смерти",
"number_update_date": "Дата обновления номера",
"actual_adr": "Адрес",
"reg_adr": "Адрес",
"temp_reg_adr": "Адрес",
"adr_update_date": "Дата обновления",
"insurance_org": "Страховая организация",
"type_insur_policy": "Тип полиса",
"begin_policy": "Дата начала полиса",
"end_policy": "Дата окончания полиса",
"notes": "Доп. информация",
"personal_state": "Семейное положение",
"work_position": "Рабочее положение",
"work_phone": "Номер телефона",
"log_name": "Логин",
"number_roommate": "Номер комнаты",
"number_relative": "Соответствующий номер",
"citizenship": "Гражданство",
"job_place": "Место работы",
"job_vacancy": "Вакансия",
"job_processing_history": "Прежние места работы",
"request_date": "Дата запроса",
"b_address": "Место рождения",
"kp": "Код подразделения",
"registration_date": "Дата регистрации (создания)",
"registered_at": "Дата регистрации (создания)",
"last_visited_at": "Дата последней авторизации",
"secret": "Секретное слово",
"kor_schet": "Корреспондентский счёт",
"ras_schet": "Расчетный счёт",
"orders": "Заказы",
"account": "Логин",
"web": "WEB-адрес",
"twitter": "Твиттер"
}